

spring:
  application:
    name: enrollment-service
  datasource:
    url: jdbc:postgresql://localhost:5432/enrollment_service
    username: postgres
    password: khoaidaica123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8084

eureka:
  instance:
    client:
      serverUrl:
        defaultZone: http://localhost:8761/eureka/